pipeline{
   agent any

   stages{

        stage('Clean'){
            steps{
                dir('api-gateway'){
                    sh './gradlew clean'
                }
            }
        }

        stage('Test'){
            steps{
                  dir('api-gateway'){
                     sh './gradlew test'
                }
            }
        }

        stage('Build'){
            steps{
                    dir('api-gateway'){
                     sh './gradlew build'
                }
            }
        }

        stage('Sonar'){
            steps{
                    dir('api-gateway'){
                     sh './gradlew sonar'
                }
            }
        }

        stage('Publish'){
             steps{
                     dir('api-gateway'){
                      sh './gradlew publish'
                 }
            }
        }
   }
}