pipeline{
   agent any

   stages{

        stage('Clean'){
            steps{
                dir('api-gateway'){
                    sh './gradlew clean'
                }
            }
        }

        stage('Test'){
            steps{
                  dir('api-gateway'){
                     sh './gradlew test'
                }
            }
        }

        stage('Build'){
            steps{
                    dir('api-gateway'){
                     sh './gradlew build'
                }
            }
        }
   }

}