version: '3'
services:

  nexus-server:
    build:
      dockerfile: Dockerfile-NexusServer
      context: /
    # specifying the image-name for the image built using dockerfile
    image: "nexus-server"
    container_name: "nexus-server"
    networks:
      - api-pet
    ports:
      - "8081:8081"

  sonar-server:
    # specifying the image-name for the image built using dockerfile
    image: "sonarqube:latest"
    container_name: "sonarqube"
    networks:
      - api-pet
    ports:
      - "9000:9000"

  jenkins-server:
    image: "docker:dind"
    container_name: "jenkins"
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_ACCESS_TOKEN=${DOCKER_HUB_ACCESS_TOKEN}
    volumes:
      - ${HOME}/jenkins-docker-certs:/certs/client
      - ${HOME}/jenkins-data:/var/jenkins_home
      - ${PWD}/jenkins-init.sh:/developer/jenkins-init.sh
    ports:
      - "8080:8080"
    networks:
      - api-pet

networks:
  api-pet:
    external: true
