restClient:
  masterService: ${API_MASTER_SERVICE_URL}
  petService: ${API_PET_SERVICE_URL}

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    loggers:
      enabled: true
    health:
      enabled: true

SwaggerConfig:
  info:
    title: "Pet Micro-service API Contract"
    summary: ""
    description: "REST api contract for Pet micro-service project"
    version: "0.0.1"
  contact:
    name: "Shubham Kesri"
    email: "shubhamkeshari90@gmail.com"
    url: "https://www.linkedin.com/in/shubhamkesri"
  servers:
    - url: "http:localhost:8000"
      description: "The local server spun up on the local machine"

spring:
  application:
    name: api-gateway

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
