version: '3'
services:

  masterDB:
    image: mongo
    container_name: "mongoDB"
    networks:
      - api-pet

  database-client:
    image: mongo-express
    container_name: "mongo-express"
    depends_on:
      - masterDB
    restart: always
    ports:
      - "8082:8081"
    networks:
      - api-pet
    environment:
      ME_CONFIG_MONGODB_SERVER: masterDB

# need to get the image name rectified
  api-master-details:
    build: .
    # specifying the image-name for the image built using dockerfile
    image: "api-master-details"
    container_name: "master-service"
    networks:
      - api-pet
    ports:
      - "8002:8002"

networks:
  api-pet:
    external: true
