pipeline{
    agent any

    stages{
        stage('Clean'){
            steps{
               dir('api-master-details'){
                  sh './gradlew clean'
               }
            }
        }

        stage('Test'){
             steps{
                 dir('api-master-details'){
                    sh './gradlew test'
                }
            }
        }

        stage('Build'){
             steps{
                 dir('api-master-details'){
                    sh './gradlew build'
                }
            }
        }

        stage('Sonar'){
             steps{
                 dir('api-master-details'){
                    sh './gradlew sonar'
                }
            }
        }

        stage('Publish'){
             steps{
                 dir('api-master-details'){
                    sh './gradlew publish'
                }
            }
        }

        stage('Docker-image'){
             steps{
                 dir('api-master-details'){
                   sh './gradlew buildAndTagDockerImage'
                 }
             }
        }

        stage('Docker-image push'){
             steps{
                 dir('api-master-details'){
                   sh './gradlew pushDockerImage'
                   sh './gradlew logoutDocker'
                 }
             }
        }
    }
}