apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api-gateway
  template:
    metadata:
      labels:
        service: api-gateway
    spec:
      containers:
        - image: kshubhamm/api-gateway:0.0.2
          name: gateway-service
          ports:
            - containerPort: 8000
          env:
            - name: API_MASTER_SERVICE_URL
              # not using fqdn as I am using default namespace
              value: "http://master-cluster-ip-service:8002/api-master-details"
            - name: API_PET_SERVICE_URL
              value: "http://pet-cluster-ip-service:8003/api-pet-details"

