apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      service: api-gateway
  template:
    metadata:
      labels:
        service: api-gateway
    spec:
      containers:
        - image: kshubhamm/api-gateway:0.0.1
          name: gateway-service
          ports:
            - containerPort: 8000
          env:
            - name: API_MASTER_SERVICE_URL
              value: master-cluster-ip-service
            - name: API_PET_SERVICE_URL
              value: pet-cluster-ip-service

