# automatic index creation is by-default off, so this needs to be turned on for
# @Indexed to work fine
spring:
  data:
    mongodb:
      auto-index-creation: true
      host: ${HOST_MONGODB_SERVER}
      port: ${PORT_MONGODB_SERVER}
      database: masterDB
  application:
    name: master-service

server:
  port: 8002

SwaggerConfig:
  info:
    title: "Master Micro-service API"
    summary: ""
    description: "REST api documentation for Master micro-service"
    version: "0.0.1"
  contact:
    name: "Shubham Kesri"
    email: "shubhamkeshari90@gmail.com"
    url: "https://www.linkedin.com/in/shubhamkesri"
  servers:
    - url: "http:localhost:8002"
      description: "The local server spun up on the local machine"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"