# automatic index creation is by-default off, so this needs to be turned on for
# @Indexed to work fine
spring:
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: masterDB
server:
  port: 8002