version: '3'
services:
  jenkins:
    build: .
    image: "jenkins-docker"
    container_name: "jenkins"
    privileged: true
    ports:
      - "50000:50000"
      - "8082:8080"
      # to access the daemon running inside the jenkins
      - "2376:2376"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ${HOME}/jenkins:/var/jenkins_home
      - ${HOME}/jenkins-docker-certs:/certs/client:ro"
    networks:
      - api-pet


networks:
  api-pet:
    external: true
